### ISSUE TITLE
Missing README file

### ISSUE THREAD

**Issue by Bujnyy** [HiczHicz/Projekt1SO#1]
## Description
The repository is missing a README file. A README file is essential for providing information about the project, including setup instructions, usage guidelines, and contributing details.

## Suggested Solution
Add a README.md file to the repository with basic information about the project, such as:
- Project purpose
- Installation instructions
- How to use the project
- Contribution guidelines

This will help new users and developers understand the project better.

**Comment by HiczHicz** [comment]
wiedziałam że to zbyt sus że RStudio samo mi zrobiło repozytorium na githubie, mogłam się domyśleć że zrobi je publiczne
